// Regenerates the public project inventory from the GitHub API.
//
//   node inventory.mjs            -> PROJECTS.md, assets/languages-*.svg
//
// Only public repositories are read (GET /users/:user/repos returns public
// repositories, and private ones are filtered out again defensively).
// A token is optional and only raises the rate limit: GITHUB_TOKEN, else
// `gh auth token` if the GitHub CLI is installed. Output is sorted and carries
// no timestamps, so a re-run with no upstream changes produces no diff.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { color as c, text, measure, svgDoc } from './lib/brand.mjs';

const ROOT = path.resolve('..');
const cfg = JSON.parse(fs.readFileSync('profile.json', 'utf8'));
const USER = cfg.user;

function token() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN;
  try {
    return execFileSync('gh', ['auth', 'token'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return '';
  }
}
const TOKEN = token();

async function gh(url) {
  const res = await fetch(`https://api.github.com${url}`, {
    headers: {
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
    },
  });
  if (!res.ok) throw new Error(`GET ${url}: HTTP ${res.status} ${await res.text()}`);
  return res.json();
}

async function publicRepos() {
  const all = [];
  for (let page = 1; ; page++) {
    const batch = await gh(`/users/${USER}/repos?type=owner&sort=full_name&per_page=100&page=${page}`);
    all.push(...batch);
    if (batch.length < 100) break;
  }
  return all.filter((r) => !r.private && r.visibility === 'public' && !cfg.exclude.includes(r.name));
}

/* ---------- fetch ---------- */
const repos = await publicRepos();
const langs = {};
for (const r of repos) langs[r.name] = await gh(`/repos/${USER}/${r.name}/languages`);
const byName = Object.fromEntries(repos.map((r) => [r.name, r]));
console.log(`public repositories: ${repos.length} (excluding ${cfg.exclude.join(', ')})`);

/* ---------- PROJECTS.md ---------- */
const placed = new Set();
const mainLang = (name) => {
  const entries = Object.entries(langs[name] || {}).sort((a, b) => b[1] - a[1]);
  return entries.length ? entries[0][0] : '—';
};
const esc = (s) => (s || '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const row = (name) => {
  const r = byName[name];
  placed.add(name);
  const note = cfg.notes[name] ? ` <sub>${cfg.notes[name]}</sub>` : '';
  return `| [${name}](${r.html_url}) | ${esc(r.description) || '—'}${note} | ${mainLang(name)} |`;
};
let md = `<!-- Generated by tools/inventory.mjs from public GitHub data. Edit tools/profile.json, not this file. -->

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="assets/hellpuff-wordmark.svg">
  <img src="assets/hellpuff-wordmark-ink.svg" alt="hellpuff" height="36">
</picture>

# Public projects

Every public repository on [github.com/${USER}](https://github.com/${USER}), grouped by what it does.
Descriptions are the repositories' own. Commercial products live in private repositories and are
described on [hellpuff.dev](https://www.hellpuff.dev) instead.

`;
for (const cat of cfg.categories) {
  const names = cat.repos.filter((n) => byName[n]);
  if (!names.length) continue;
  md += `## ${cat.title}\n\n${cat.blurb}\n\n| Repository | What it does | Language |\n| :-- | :-- | :-- |\n`;
  md += names.map(row).join('\n') + '\n\n';
}
const uncurated = repos.map((r) => r.name).filter((n) => !placed.has(n)).sort();
if (uncurated.length) {
  md += `## Not yet curated\n\nNew public repositories that have not been placed in a category in \`tools/profile.json\`.\n\n| Repository | What it does | Language |\n| :-- | :-- | :-- |\n`;
  md += uncurated.map(row).join('\n') + '\n\n';
}
md += `---\n\n<sub>${repos.length} public repositories. Regenerate with \`cd tools && npm run inventory\`.</sub>\n`;
fs.writeFileSync(path.join(ROOT, 'PROJECTS.md'), md);
if (uncurated.length) console.log(`uncurated (add to profile.json): ${uncurated.join(', ')}`);

/* ---------- languages strip ---------- */
const IGNORE = new Set(['HTML', 'CSS', 'Shell', 'Makefile', 'Dockerfile', 'Batchfile', 'Procfile', 'CMake']);
const early = new Set(cfg.categories.find((x) => x.title === 'Early work')?.repos || []);
const totals = {};
for (const [name, l] of Object.entries(langs)) {
  if (early.has(name)) continue;
  for (const [k, v] of Object.entries(l)) if (!IGNORE.has(k)) totals[k] = (totals[k] || 0) + v;
}
const sum = Object.values(totals).reduce((a, b) => a + b, 0);
const ranked = Object.entries(totals).sort((a, b) => b[1] - a[1]);
const top = ranked.slice(0, 5);
const rest = ranked.slice(5).reduce((a, [, v]) => a + v, 0);
if (rest) top.push(['Other', rest]);

for (const [variant, fg, muted, accent, ramp] of [
  ['dark', c.paper, c.silver, c.emerald, ['#3FBF8A', '#D9D5CC', '#A3AAA6', '#737A77', '#4E5452', '#343937']],
  ['light', c.inkText, c.inkMuted, c.forest, ['#14724F', '#2A2E2D', '#5B615E', '#878D8A', '#B0B5B2', '#D2D5D3']],
]) {
  const W = 720, gap = 3, perRow = 3, colW = W / perRow;
  const H = 72 + Math.ceil(top.length / perRow) * 30;
  let x = 0;
  const segs = [], legend = [];
  top.forEach(([name, v], i) => {
    const w = Math.max(2, (v / sum) * (W - gap * (top.length - 1)));
    segs.push(`<rect x="${x.toFixed(1)}" y="34" width="${w.toFixed(1)}" height="8" rx="1" fill="${ramp[i]}"/>`);
    x += w + gap;
    const lx = (i % perRow) * colW, ly = 80 + Math.floor(i / perRow) * 30;
    const pct = `${((v / sum) * 100).toFixed(1)}%`;
    legend.push(`<rect x="${lx.toFixed(1)}" y="${ly - 10}" width="10" height="10" fill="${ramp[i]}"/>` +
      text('sans', name, { x: lx + 20, y: ly, size: 18, fill: fg }) +
      text('mono', pct, { x: lx + 28 + measure('sans', name, 18), y: ly, size: 15, fill: muted }));
  });
  fs.writeFileSync(path.join(ROOT, 'assets', `languages-${variant}.svg`), svgDoc({
    w: W, h: H, title: 'Public code by language',
    desc: top.map(([n, v]) => `${n} ${((v / sum) * 100).toFixed(1)}%`).join(', ') + `, measured across ${repos.length - early.size} public repositories.`,
    body: text('mono', 'PUBLIC CODE BY LANGUAGE', { x: 0, y: 16, size: 14, tracking: 0.12, fill: muted }) +
      text('mono', `${repos.length} REPOSITORIES  ·  ${ranked.length} LANGUAGES`, { x: W, y: 16, size: 14, tracking: 0.12, anchor: 'end', fill: accent }) +
      segs.join('') + legend.join(''),
  }));
}

console.log(`languages: ${ranked.map(([k]) => k).join(', ')}`);
